//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieRekrutacyjne1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_B
    {
        public Nullable<int> Col_B1 { get; set; }
        public string Col_B2 { get; set; }
        public Nullable<int> Col_B3 { get; set; }
        public int Id { get; set; }
    }
}
