//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieRekrutacyjne1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_C
    {
        public string Col_C1 { get; set; }
        public byte[] Col_C2 { get; set; }
        public Nullable<int> Col_C3 { get; set; }
        public string Col_C4 { get; set; }
        public int Id { get; set; }
    }
}
